version: "3"

services:
  postgres:
    image: postgres:11
    container_name: trip-reservation-db
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=trip-reservation
      - POSTGRES_USER=reservation
      - POSTGRES_PASSWORD=reservation
    networks:
      - trip-reservation

networks:
  trip-reservation:
